# Generated by Django 4.2.5 on 2024-04-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_date_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='themes',
            new_name='theme',
        ),
    ]
