# Generated by Django 4.2.5 on 2024-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_themes_news_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsthemes',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
