# Generated by Django 4.2.5 on 2024-04-23 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comments_date_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date_pub',
        ),
        migrations.AddField(
            model_name='comments',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 23, 13, 45, 16, 673122)),
        ),
    ]
